import { ThemeProvider } from '@/theme/ThemeProvider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='w-full h-screen'>
        <ThemeProvider>
          <main className='w-full h-screen bg-slate-50 dark:bg-slate-600'>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
